### ISSUE TITLE
delta packet not found error

### ISSUE THREAD

**Issue by FlowingSPDG** [theikkila/csgo-broadcast#1]
Hi! I'm Japanese CS:GO tournament organizer.
I've tried  this program. It allows to use HLAE Smooth in real low latency.
but,it has little problem.

When broadcast program received the packet from CS:GO Server,This program will make fragment file for CS:GO client.
but,sometime program will return fragments number before creating fragment file.
so,we will lost connection to broadcast.

When I changed cvar(tv_broadcast_keyframe_interval 0.5. def=3) ,I can connect playcast little bit longer.
So, the program needs to return fragment number **AFTER** creating fragment file. Please fix.

Sorry for bad english.
Thanks.

**Comment by theikkila** [comment]
Hi! @ruk1ium thanks for reporting this!
This project is not actively maintained but there is not actually very much maintaining so It's probably safe to use it.

Your problem sounds like a race condition with database write and fragent write and I've fixed that in #2 

I'm currently unable to repeat that problem so I would be glad that you test that branch out and report if it fixes the problem. I'll merge it after that.

If you're using the server publicly large audience I suggest that you have some caching loadbalancer in front of that

**Comment by FlowingSPDG** [comment]
Thanks for replying!

Okay,I'm gonna test new branch. but I have to organize the tournament for server testing. so it may takes few weeks,sorry...
When I'm done testing,I'll report you again.

I'll try it.Thanks!

**Comment by FlowingSPDG** [comment]
You may need to create "datas" folder before "npm start".
Please add "datas" folder in git branch. Thanks

**Comment by FlowingSPDG** [comment]
@theikkila 
[gotvlog.txt](https://github.com/theikkila/csgo-broadcast/files/1935638/gotvlog.txt)
I've tested and the problem does not fixed.
CSGO Console is spamming this error.

```
734.02. Playcast cannot retrieve fragment 404, retrying
Update delta not found.
```

I tried with 3 CSGO Clients but all of them lost connection.
I attached log file.

This is the hosted url.
http://gotv.lo3.live:3000/
